User_Authentication/Login_app/urls.py
from django.urls import path
from Login_app import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static 


app_name = 'Login_app'

urlpatterns = [
    path('' , views.index , name = 'index'),
    path('register/' , views.register , name = 'register'),
    path('login/' , views.login_page , name = 'login_page'),
    path('user_login/' , views.user_login , name = 'user_login'),
    path('user_logout' , views.user_logout , name = 'user_logout')
]

# urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL , documet_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User_Authentication/User_Authentication/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('Login_app.urls'))
    
]

User_Authentication/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserInfo(models.Model) :

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_info')

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to="profile_pics" , blank=True)


    def __str__(self) :
        from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserInfo(models.Model) :

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_info')

    facebook_id = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to="profile_pics" , blank=True)


    def __str__(self) :
        return self.user.username

User_Authentication/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username", "email", "password")  



class UserInfoForm(forms.ModelForm) :
    class Meta() :
        model = UserInfo
        fields = ("facebook_id" , 'profile_pic')

User_Authentication/Login_app/views.py
from django.shortcuts import render
from Login_app.forms import UserForm , UserInfoForm
from Login_app.models import UserInfo
from django.contrib.auth.models import User

from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponseRedirect , HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.


def login_page(request) :
    diction = {}
    return render(request , 'Login_app/login.html' , context=diction)
   
def user_login(request) :

    diction = {}

    if request.method == 'POST' :
        uername = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = uername , password = password)

        if user :
            if user.is_active :
                login(request , user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else :
                return HttpResponse("Account is not ative!")
            
        else :
            return HttpResponse('Ligin details are wrong!')
        
    else :
        HttpResponseRedirect(reverse("Login_app:login_apge"))
        
    
@login_required
def user_logout(request) :
    logout(request)
    return HttpResponseRedirect(reverse("Login_app:index"))


def index(request) :

    diction = {}

    if request.user.is_authenticated :
        current_user = request.user
        user_id = current_user.id 
        user_base_info = User.objects.get(pk = user_id)
        user_more_info = UserInfo.objects.get(user__pk = user_id)
        diction = {'user_base_info': user_base_info , 'user_more_info': user_more_info}

    return render(request , 'Login_app/index.html' , context=diction)


def register(request) :

    registered = False

    if request.method == 'POST' :
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES :
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True

    else :
        user_form = UserForm()
        user_info_form = UserInfoForm()

    diction = {'user_form' : user_form , 'user_info_form' : user_info_form , 'registered' : registered}

    return render(request , 'Login_app/register.html' , context=diction)

User_Authentication/templates/Login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary" >
        <div class="container-fluid">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Login_app:index' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Login_app:user_logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Login_app:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Login_app:login_page' %}">Login</a>
              </li>
              {% endif %}
            </ul>

        </div>
      </nav>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" ></script>

    <div class="container" style="padding-top: 20px;">

         {% block body_block  %}

          {% endblock  %}
    </div>
    
</body>
</html>

User_Authentication/templates/Login_app/index.html
<!DOCTYPE html>

{% extends "Login_app/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body" style="text-align: center;">
                    <p>Username: {{ user_base_info.username }}</p>
                    <p>Email: {{ user_base_info.email }}</p>
                    <p><a href="{{ user_more_info.facebook_id }}" class="btn btn-success btn-sm">Facebook Id</a></p>
                    <p><img src="/media/{{ user_more_info.profile_pic }}" class="img-fluid" width="150px"></p>
                </div>
            </div>
        </div>
    </div>
</div>


{% else %}

<div class = "alert alert-primary">You are not logged in!!</div>

{% endif %}
  
{% endblock %}

User_Authentication/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}

{% block body_block %}

<h4>Login Page :</h4>

<form action="{% url 'Login_app:user_login' %}" method = 'POST'>
    <label for="username">Username : </label>
    <input type="text" name = 'username' placeholder="Enter Username.." required class="form-control">
    <label for="password">Password : </label>
    <input type="password" name = 'password' placeholder="Enter Password.." required class="form-control">
    {% csrf_token %}
    <br>
    <input type="submit" name = 'submit' value = 'Login' class = 'btn btn-success btn-sm'>
</form>
  
{% endblock  %}

User_Authentication/templates/Login_app/register.html
{% extends "Login_app/base.html" %}
(% load staticfiles %)

{% block body_block %}

{% if registered %}

<div class="alert alert-success">Congratulation! Registration Sucessfull!</div>

 {% else %} 
<form method = "POST" enctype="multipart/form-data">

    {{user_form.as_p}}
    {{user_info_form.as_p}}
    {% csrf_token %}

    <input type="submit" name = 'submit' value="Register" class = 'btn btn-primary btn-sm'>

</form>
{% endif %}
  
{% endblock %}